[package]
name = "domain_checker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
clap = { version = "3.0" }
lazy_static = "1.4"



